### ISSUE TITLE
(sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by YukiSakuma** [happypandax/server#44]
Happens in 0.0.2 to .4, HP was able to successfully export the database though, like the popup closed after 100% etc. I was able to import to HPX successfully back then.

HP log 
`INFO   io_misc Finished exporting galleries!`

**Comment by Pewpews** [comment]
Please describe the issue more clearly. What are you trying to do? Are you tying to convert from HP to HPX?
What does the conversion script output?

**Comment by YukiSakuma** [comment]
Yes I am trying to convert? conversion script output?
I think this one? "(sqlite3.OperationalError) unable to open database file" and then it just stops there.

**Comment by Pewpews** [comment]
I want to see what appears before `"(sqlite3.OperationalError) unable to open database file` too.
Make sure you're pointing to a valid database file. Don't point it to the `.hpdb` file HP produces. 

If you're using the GUI you should see the output here: 
![image](https://user-images.githubusercontent.com/11841002/35011118-67f499f2-fb05-11e7-88a1-6eef05182104.png)

**Comment by YukiSakuma** [comment]
Yeah I'm pointing it to the happypanda.db file
```
>: Destination:
>: data\happypanda.db
>: RARtool path:
>: bin\win32\unrar.exe
>: Process count:
>: 3
>: Connecting to Happypanda database..
>: Fetching gallery lists..
>: Fetching all galleries, chapters, tags and hashes..
>: Fetched galleries count:
>: 10*
>: Creating new Happypanda X database
>: (sqlite3.OperationalError) unable to open database file
```
*just tested that the number of galleries seems independent of the error

**Comment by Pewpews** [comment]
Okay, try this:
1. Open a CMD and cd to where HPX is installed `cd path/to/hpx/folder`
2. Run this: `./HPtoHPX.exe -r bin/win32/unrar.exe path/to/hp/db/file.db data/happypanda.db`

Replace 'path/to/hp/db/file.db' with path to the HP db.

**Comment by YukiSakuma** [comment]
here's the output in cmd
```
Source:  happypanda.db
Destination:  data/happypanda.db
RARtool path:  bin/win32/unrar.exe
Process count:  3
Connecting to Happypanda database..
Fetching gallery lists..
Fetching all galleries, chapters, tags and hashes..
Fetched galleries count: 10
Creating new Happypanda X database
(sqlite3.OperationalError) unable to open database file
Traceback (most recent call last):
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_po
ol_connect
  File "env\lib\site-packages\sqlalchemy\pool.py", line 387, in connect
  File "env\lib\site-packages\sqlalchemy\pool.py", line 766, in _checkout
  File "env\lib\site-packages\sqlalchemy\pool.py", line 516, in checkout
  File "env\lib\site-packages\sqlalchemy\pool.py", line 1229, in _do_get
  File "env\lib\site-packages\sqlalchemy\pool.py", line 333, in _create_connecti
on
  File "env\lib\site-packages\sqlalchemy\pool.py", line 461, in __init__
  File "env\lib\site-packages\sqlalchemy\pool.py", line 651, in __connect
  File "env\lib\site-packages\sqlalchemy\engine\strategies.py", line 105, in con
nect
  File "env\lib\site-packages\sqlalchemy\engine\default.py", line 393, in connec
t
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "HPtoHPX.py", line 1121, in <module>
  File "HPtoHPX.py", line 804, in main
  File "env\lib\site-packages\sqlalchemy\sql\schema.py", line 3949, in create_al
l
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 1928, in _run_vis
itor
  File "contextlib.py", line 59, in __enter__
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 1921, in _optiona
l_conn_ctx_manager
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in contextu
al_connect
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 2151, in _wrap_po
ol_connect
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 1465, in _handle_
dbapi_exception_noconnection
  File "env\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_fro
m_cause
  File "env\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "env\lib\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_po
ol_connect
  File "env\lib\site-packages\sqlalchemy\pool.py", line 387, in connect
  File "env\lib\site-packages\sqlalchemy\pool.py", line 766, in _checkout
  File "env\lib\site-packages\sqlalchemy\pool.py", line 516, in checkout
  File "env\lib\site-packages\sqlalchemy\pool.py", line 1229, in _do_get
  File "env\lib\site-packages\sqlalchemy\pool.py", line 333, in _create_connecti
on
  File "env\lib\site-packages\sqlalchemy\pool.py", line 461, in __init__
  File "env\lib\site-packages\sqlalchemy\pool.py", line 651, in __connect
  File "env\lib\site-packages\sqlalchemy\engine\strategies.py", line 105, in con
nect
  File "env\lib\site-packages\sqlalchemy\engine\default.py", line 393, in connec
t
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open datab
ase file
[16108] Failed to execute script HPtoHPX

```

**Comment by Pewpews** [comment]
Does a folder named `data` exists in the HPX folder? If not, create it and retry.

**Comment by YukiSakuma** [comment]
That fixed it! To think that was the cause but I am using the hpx win zip download and there's no data folder inside it.
Thanks!

**Comment by Pewpews** [comment]
That's an error on my part. Thanks for reporting. Fixed in the next release.
