### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by Klein69** [happypandax/server#47]
![immagine](https://user-images.githubusercontent.com/27512463/35991770-810944d2-0d08-11e8-8088-54bd2a3f55c2.png)

**Comment by Pewpews** [comment]
Hello,
I'm not sure what you expect I do/can do with this limited information.

**Comment by Klein69** [comment]
Hi 
Sorry for my english 

I installed happypanda0.0.6.exe
Start Server and what appears in the image appears to me
error.log is empty.

I do not know if it serves     Activity.log:
09-02 16:34 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:34:03] "GET / HTTP/1.1" 500 412 9.021805
09-02 16:34 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:34:12] "GET /favicon.ico HTTP/1.1" 500 412 9.025671
09-02 16:35 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:35:06] "GET / HTTP/1.1" 500 412 9.044165
09-02 16:35 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:35:15] "GET /favicon.ico HTTP/1.1" 500 412 9.049291
09-02 16:42 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:42:19] "GET / HTTP/1.1" 500 412 9.040844
09-02 16:42 INFO       geventwebsocket.handler ::1 - - [2018-02-09 16:42:28] "GET /favicon.ico HTTP/1.1" 500 412 9.034836


By google translate 
thank you

**Comment by Pewpews** [comment]
Please wait for `v0.0.7` to collect more info. It might also have been fixed in there.

**Comment by Pewpews** [comment]
Please try again in `v0.0.7`

**Comment by Klein69** [comment]
hi 
Happypandax 0.0.7   Error.log:
11-02 22:30 ERROR      happypanda.core.web.views Unknown exception occurred in views 
Traceback (most recent call last):
  File "happypanda\core\web\views.py", line 233, in app_base
  File "happypanda\core\web\views.py", line 102, in is_same_machine
  File "gevent\_socketcommon.py", line 302, in gethostbyaddr
  File "gevent\resolver_thread.py", line 68, in gethostbyaddr
  File "gevent\pool.py", line 325, in apply
  File "gevent\event.py", line 385, in get
  File "gevent\event.py", line 375, in get
  File "gevent\event.py", line 355, in _raise_exception
  File "gevent\_compat.py", line 33, in reraise
  File "gevent\threadpool.py", line 211, in _worker
socket.herror: [Errno 11004] host not found
11-02 22:30 ERROR      happypanda.core.web.views Unknown exception occurred in views 
Traceback (most recent call last):
  File "happypanda\core\web\views.py", line 233, in app_base
  File "happypanda\core\web\views.py", line 102, in is_same_machine
  File "gevent\_socketcommon.py", line 302, in gethostbyaddr
  File "gevent\resolver_thread.py", line 68, in gethostbyaddr
  File "gevent\pool.py", line 325, in apply
  File "gevent\event.py", line 385, in get
  File "gevent\event.py", line 375, in get
  File "gevent\event.py", line 355, in _raise_exception
  File "gevent\_compat.py", line 33, in reraise
  File "gevent\threadpool.py", line 211, in _worker
socket.herror: [Errno 11004] host not found

**Comment by Pewpews** [comment]
What's your OS?

**Comment by Klein69** [comment]
windows 10

**Comment by Pewpews** [comment]
Can you open CMD or Powershell, write `ipconfig` and tell me if you have a block that looks like this:
![714 powershell_2018-02](https://user-images.githubusercontent.com/11841002/36078955-6f9e5308-0f75-11e8-8986-e6e1b6201015.png)

**Comment by Klein69** [comment]
![immagine](https://user-images.githubusercontent.com/27512463/36078996-60e57fcc-0f7e-11e8-81ae-f4b76ac4fc94.jpg)

**Comment by Pewpews** [comment]
Again, in CMD or Powershell, what's the output of `hostname` and `wmic computersystem  get name`.

**Comment by Klein69** [comment]
![immagine](https://user-images.githubusercontent.com/27512463/36079675-113ceb1a-0f86-11e8-8b3f-3ae740b2878c.png)

**Comment by Pewpews** [comment]
Will be resolved in `v0.0.8`. Thanks for reporting.
